language: c
sudo: required
install: test -e .travis.opam.sh || wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script:
- bash -ex .travis-opam.sh
env:
  matrix:
    - OCAML_VERSION="4.08" PACKAGE="async-uri"
    - OCAML_VERSION="4.09" PACKAGE="async-uri"
os:
- linux
